version: '{build}-{branch}'

branches:
    only:
        - master

image: Visual Studio 2019

configuration: Release

platform: x64

environment:
    CMAKE_GENERATOR: Visual Studio 16 2019
    BUILD_FOLDER: build

before_build:
    - mkdir %BUILD_FOLDER%
    - cd %BUILD_FOLDER%
    - cmake -G "%CMAKE_GENERATOR%" ..

build:
    project: galToolbox.sln
    parallel: true
    verbosity: normal
