version: '{build}-{branch}'

image: 
    - Visual Studio 2019

platform:
    - x64

configuration:
    - Release

environment:
    GTEST_VERSION: 1.11.0
    CMAKE_GENERATOR: Visual Studio 16 2019

before_build:
    - echo "project build at %APPVEYOR_BUILD_FOLDER%"

    - rm -r %APPVEYOR_BUILD_FOLDER%\3rd-party\googletest\lib
    - mkdir %APPVEYOR_BUILD_FOLDER%\3rd-party\googletest\lib

    - curl -fsSL -o release-%GTEST_VERSION%.zip https://github.com/google/googletest/archive/release-%GTEST_VERSION%.zip
    - unzip -q release-%GTEST_VERSION%.zip
    - cd googletest-release-%GTEST_VERSION%

    - mkdir build
    - cd build

    - cmake
        -G "%CMAKE_GENERATOR%"
    - cmake --build . --config Release -- /m

    - copy lib\Release\gtest.lib %APPVEYOR_BUILD_FOLDER%\3rd-party\googletest\lib
    - copy lib\gtest\Release\gtest_main.lib %APPVEYOR_BUILD_FOLDER%\3rd-party\googletest\lib
    - cd %APPVEYOR_BUILD_FOLDER%

build:
    parallel: true
    project: %APPVEYOR_BUILD_FOLDER%\%APPVEYOR_PROJECT_NAME%.sln
